# -*- coding: utf-8 -*-
"""data-setBigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1js_ikxoCrVr8DoxRhlNExZ9s5Lthyzw_

Para começar, vamos criar o banco de dados "vacinados", utilizando os dados da API do data-set escolhido.
"""

import requests
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt


def create_vacinados_db():
    # URL da API
    url = f"http://dados.recife.pe.gov.br/api/3/action/datastore_search?&resource_id=ca7fb968-3a2c-44ff-a2e8-730d1a689407&limit=300000"

    # Fazer a requisição à API
    response = requests.get(url)
    data = response.json()

    if 'result' in data and 'records' in data['result']:
        vacinados = data['result']['records']
    else:
        print("Erro: Não foi possível obter os dados da API.")
        return


    # Criar ou conectar ao banco de dados SQLite
    conn = sqlite3.connect('vacinados.db')
    c = conn.cursor()

    # Criar a tabela, se não existir
    c.execute('''
    CREATE TABLE IF NOT EXISTS vacinados (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    faixa_etaria TEXT,
    idade NUMERIC,
    sexo TEXT,
    raca_cor TEXT,
    municipio TEXT,
    grupo TEXT,
    categoria TEXT,
    lote TEXT,
    vacina_fabricante TEXT,
    descricao_dose NUMERIC,
    cnes TEXT,
    sistema_origem TEXT,
    data_vacinacao TIMESTAMP
    );
    ''')



    # Inserir dados no banco de dados
    for vacina in vacinados:
        c.execute('''
        INSERT INTO vacinados (faixa_etaria, idade, sexo, raca_cor, municipio, grupo, categoria, lote, vacina_fabricante, descricao_dose, cnes, sistema_origem, data_vacinacao)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
        ''', (
            vacina.get('faixa_etaria', ''),
            vacina.get('idade', 0),
            vacina.get('sexo', ''),
            vacina.get('raca_cor', ''),
            vacina.get('municipio', ''),
            vacina.get('grupo', ''),
            vacina.get('categoria', ''),
            vacina.get('lote', ''),
            vacina.get('vacina_fabricante', ''),
            vacina.get('descricao_dose', 0),
            vacina.get('cnes', ''),
            vacina.get('sistema_origem', ''),
            vacina.get('data_vacinacao', '')
        ))

    # Commitar as mudanças e fechar a conexão
    conn.commit()
    conn.close()

# Exemplo de uso chamando a função para criar com todos os registros da API
create_vacinados_db()

"""Agora vamos criar uma nova conexão com o banco de dados para fazermos consultas:"""

connection = sqlite3.connect('vacinados.db')

# Criando uma variavel que recebe todo o valor da leitura

vc = pd.read_sql_query("select * from vacinados where municipio like '%recife%';", connection)

"""Vamos começar nossa análise exploratória:"""

vc.info()
# um comando que vai dar as informações gerais da nossa base de dados, valores nulos e tipos de dados.

"""Agora outro comando que nos fornece um resumo estatistico do nosso banco:

Contagem (count): número de observações não nulas.

Média (mean): média aritmética dos valores.

Desvio padrão (std): medida de dispersão em torno da média.

Valor mínimo (min): menor valor na variável.

Quartis (25%, 50%, 75%): valores que dividem a distribuição em quartis, representando o primeiro quartil (Q1), mediana (Q2) e terceiro quartil (Q3).

Valor máximo (max): maior valor na variável.
"""

vc.describe()

"""Agora vamos utilizar o comando display para mostrar os 5 primeiros e os 5 últimos dados e também a quantidade de informações que temos:"""

display(vc)

"""Agora para visualizar o periodo da analise:"""

inicio = pd.to_datetime(vc['data_vacinacao']).dt.date.min()
print("Data de inicio", inicio)
fim = pd.to_datetime(vc['data_vacinacao']).dt.date.max()
print("Data final", fim)

"""# Consultas de dados"""

pd.read_sql("select * from vacinados where sexo like '%outros%'", connection)

"""Exibição de grafico das vacinas fabricadas por mais usadas"""

vc_vacina = vc.vacina_fabricante.value_counts()
vc_vacina.plot(kind='bar')
plt.xlabel('Nome da vacina')
plt.ylabel('Numero dos vacinados')
plt.show()

vc_sexo = vc.sexo.value_counts()
vc_sexo.plot(kind='bar')

vc_idade = vc.faixa_etaria.value_counts()
vc_idade.plot(kind='bar')
plt.xlabel('Faixa etária')
plt.ylabel('Vacinados')
plt.show()

vc_grupo = vc.grupo.value_counts().head(10)
vc_grupo.plot(kind='barh', color='skyblue')
plt.xlabel('Grupo')
plt.ylabel('Vacinados')
plt.show()

def get_vacinados_data():
    conn = sqlite3.connect('vacinados.db')
    query = "SELECT data_vacinacao FROM vacinados"
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df
def plot_vacinados_por_mes_ano():
    df = get_vacinados_data()

    # Converter a coluna 'data_vacinacao' para o formato datetime
    df['data_vacinacao'] = pd.to_datetime(df['data_vacinacao'])

    # Extrair o mês e o ano
    df['mes_ano'] = df['data_vacinacao'].dt.to_period('M')

    # Agrupar por mês e ano e calcular a contagem de vacinados
    vacinados_por_mes_ano = df.groupby('mes_ano').size()

    # Plotar o gráfico
    plt.figure(figsize=(10, 6))
    vacinados_por_mes_ano.plot(kind='line', marker='o', linestyle='-')

    # Marcar o mínimo
    minimo = vacinados_por_mes_ano.min()
    plt.axhline(y=minimo, color='r', linestyle='--', label=f'Mínimo: {minimo}')
    plt.legend()

    maximo = vacinados_por_mes_ano.max()
    plt.axhline(y=maximo, color='g', linestyle='--', label=f'Máximo: {maximo}')
    diff = maximo - minimo

    # Adicionar texto indicando a diferença
    texto_diff = f'Diferença do minimo e o maximo: {diff}'
    plt.text(0.5, 0.9, texto_diff, ha='center', va='center', transform=plt.gca().transAxes, fontsize=10, bbox=dict(facecolor='white', alpha=0.5))

    plt.title('Número de Vacinados por Mês e Ano')
    plt.xlabel('Mês e Ano')
    plt.ylabel('Número de Vacinados')
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.show()


plot_vacinados_por_mes_ano()